- platform: nzbget
  host: !secret nzbget_host
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - article_cache
    - download_rate
    - download_paused
